config/routes.rb
Rails.application.routes.draw do
  post '/address', to: 'address#create'
  get '/cart', to: 'cart#index'
  post '/cart', to: 'cart#create'
  delete '/cart', to: 'cart#destroy'
  put '/cart', to: 'cart#update'
  delete '/cartAll', to: 'cart#destroyAll'
  get '/cart/checkout', to: 'cart#checkout'
  get '/cart/placeorder', to: 'cart#order', as: 'order'
  get '/allProducts', to: 'store#all'
  get '/category/:name', to: 'store#category'
  post '/store', to: 'store#filter'
  devise_for :users
  resources :products
  get '/admin/products', to: 'products#all'
  root 'store#index'
  get '/search', to: 'store#search'
  get '/orders', to: 'order#index'
  post '/orders', to: 'order#create'
  get '/orders/all', to: 'order#all'
  get '/orders/myorders/:id', to: 'order#show', as: 'order_details'
  delete '/orders/myorders/:id', to: 'order#destroy'
  post '/orders/myorders/:id/return', to: 'order#return'
  put '/orders/myorders/:id/payment', to: 'order#payment'
  put '/orders/myorders/:id/deliver', to: 'order#delivered'
end

app/models/cart.rb
class Cart < ApplicationRecord
    scope :current_user, ->(id) { where(user_id: id)}
    belongs_to :user
    belongs_to :product

    def self.current_user_cart_items(id)
        return Cart.current_user(id)
    end

    def self.calculateTotal(id)
        total = 0
        for each in Cart.current_user(id) do
           total += (each.product.price * each.quantity)
        end
        return total
    end

    def self.getProducts(id)
        result = []
        for each in Cart.current_user(id) do
            result.append({
                id: each.product.id,
                title: each.product.title,
                price: each.product.price,
                quantity: each.quantity
            })
        end
        return result
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :user_logged_in
  before_action :cart_items_exists, only: [:checkout, :order]
  before_action :check_in_stock, only: [:order, :checkout]

  def index
    @items = Cart.where(user_id: current_user.id)
  end

  def create
    @quantity = params[:quantity]
    @product_id = params[:product_id]
    
    Cart.create(user_id: current_user.id, product_id: @product_id, quantity: @quantity)
  end

  def destroy
    cart = Cart.find(params[:cart_id])
    cart.destroy
    flash[:success] = "Removed from cart successfully"
    redirect_to cart_path
  end

  def destroyAll
    Cart.where(user_id: current_user.id).destroy_all
    render :partial => "emptycart"
  end

  def update
    @quantity = params[:quantity]
    @product_id = params[:product_id]
    
    cartItem = Cart.find_by(user_id: current_user.id, product_id: @product_id)
    cartItem.update(quantity: @quantity)
  end

  def checkout
    @items = Cart.where(user_id: current_user.id)
  end

  def order
    if current_user.address.nil?
      flash[:warning] = "Your address isn't stored, please try again"
      redirect_to root_path
    end
    @address = current_user.address
    @items = Cart.where(user_id: current_user.id)
  end

  private
    def user_logged_in
      if current_user.nil?
          redirect_to root_path
      end
    end

    def cart_items_exists
      if Cart.where(user_id: current_user.id).count < 1
          flash[:success] = "Your cart is empty to checkout"
          redirect_to root_path
      end
    end

    def check_in_stock
      cart = Cart.where(user_id: current_user.id)
      for each in cart do 
        if not each.product.has_stock?
          flash[:now] = "There are no stock items in your cart, remove them"
          redirect_to cart_path
        end
      end
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_emptycart.html.erb
<div class="m-5 pt-5">
    <div class="alert alert-warning mt-5" role="alert">
        <h4>
            Your cart is empty, please 
            <%= link_to "click here", root_path, class: "text-danger" %> to continue shopping
        </h4>
    </div>
</div>

app/views/cart/checkout.html.erb
<div class="mt-5">
    <h3>
        <%= link_to "Cart items: #{@items.count}", cart_path %>
    </h3>
    <% @items.each do |item| %>
        <p class="text-muted">(<%= item.product.title %>) * <%= item.quantity %></p>
    <% end %>
    <hr />
    <div>
        <h4> Fill in your delivery address: </h4>
        <%= form_with url: '/address', method: :post, class: "addressForm" do |form| %>
            <div class="field py-2">
                <%= form.label :email, class: "form-label" %>
                <%= form.email_field :email, value: current_user.email,
                     class: "form-control", placeholder: "Email id" %>
            </div>
            <div class="field py-2">
                <%= form.label :phone, class: "form-label" %>
                <%= form.telephone_field :phone, value: current_user.phone_number,
                    class: "form-control", placeholder: "Phone number" %>
            </div>
            <div class="field py-2">
                <%= form.label :location, class: "form-label" %>
                <%= form.text_area :location, value: current_user.address ? current_user.address.location : "",
                class: "form-control", rows: 6,placeholder: "Enter location clearly" %>
            </div>
            <div class="field py-2">
                <%= form.label :zipcode, class: "form-label" %>
                <%= form.text_field :zipcode, value: current_user.address ? current_user.address.zipcode : "", 
                class: "form-control", placeholder: "zip code" %>
            </div>
            <div class="actions">
                <%= form.submit "Submit", class: "btn btn-info" %>
            </div>
        <% end %>
    </div>
</div>

app/views/cart/index.html.erb
<% flag = true %>
<% if @items.count > 0 %>
<div class="cartContainer">
    <h3> Cart items: <%= @items.count %> </h3>
    <hr/>
    <% @items.each do |item| %>
        <div class="mb-5">
            <% if not item.product.has_stock? %>
                <% flag = false %>
                <p class="text-danger">
                    The product is not in stock, you cannot checkout
                </p>
            <% end %>
            <h4> <%= link_to item.product.title , item.product %> </h4>
            <h6> Quantity: <%= item.quantity %> </h6>
            <h5> 
                Price: 
                <%= item.product.price %> * <%= item.quantity %>
                = <strong> 
                    <%= number_to_currency(item.product.price * item.quantity, unit: "₹") %> 
                </strong>
            </h5>
            <%= form_with url: "/cart", method: :delete, class: "removeCartForm" do |f| %>
                <%= f.hidden_field :cart_id, value: item.id %>
                <%= f.submit "Remove from cart",
                    class: "btn btn-outline-danger" %>
            <% end %>
            <p class="text-muted mt-2">Added to cart <%= time_ago_in_words(item.created_at) %> ago </p>
        </div>
    <% end %>
    <hr/>
    <h3> Total price: ₹<%= Cart.calculateTotal(current_user.id) %>
    </h3>
    <div class="d-flex">
        <% if flag %>
            <%= link_to 'Checkout', cart_checkout_path, 
                class: "btn btn-success" %> &nbsp; &nbsp;
        <% end %>
        <%= form_with url: '/cartAll', method: :delete, class: "removeAllCartForm" do |form| %>
            <%= form.submit "Empty cart", class: "btn btn-danger", 
                data: {confirm: "Are you sure to empty your cart"} %>
        <% end %>
    </div>
</div>
<% else %>
<div>
    <%= render 'emptycart' %>
</div>
<% end %>
<script type="text/javascript">
    $(".removeAllCartForm").on('submit', function(e){
      e.preventDefault();
      let authenticity_token = $(".removeAllCartForm input[name=authenticity_token]").val()
      let cartContainer = $(".cartContainer")

      $.ajax({
        url: '/cartAll', type: 'DELETE', dataType: 'html',
        data: {authenticity_token},
        success: function(res) {
            updateCartCount(true)
            sendToast("Cleared your cart", "Go to cart page for more details")
            cartContainer[0].innerHTML = res
        }
      })
    })
</script>

app/views/cart/order.html.erb
<div>
    <h4 class="text-center text-primary">
        |- Placing your order -|
    </h4>
    <div class="row mt-4">
        <div class="col-md-5 my-2">
            <ul class="list-group">
                <li class="list-group-item">
                    <h4> Delivery Address: </h4>
                </li>
                <li class="list-group-item">
                    <h6> Phone: <%= @address.phone %> </h6>
                </li>
                <li class="list-group-item">
                    <h6> Email: <%= @address.email %> </h6>
                </li>
                <li class="list-group-item">
                    <h6> Zip code: <%= @address.zipcode %> </h6>
                </li>
                <li class="list-group-item">
                    <h6> Address: <%= @address.location %> </h6>
                </li>
            </ul>
        </div>
        
        <div class="col-md-6 my-2">
             <ul class="list-group">
                <li class="list-group-item">
                    <h4> Cart Items: </h4>
                </li>
                <% @items.each do |item| %>
                    <li class="list-group-item">
                        <h6> Ordering: <%= item.product.title %> </h6>
                        <p class="text-muted">
                            Price breakup: <%= "#{item.product.price} * #{item.quantity}" %>
                        </p>
                    </li>
                <% end %>
                <li class="list-group-item">
                    <h5> Total price: <%= Cart.calculateTotal(current_user.id) %> </h5>
                </li>
            </ul>
        </div>
    </div>

    <div class="mt-4">
        <%= form_with url: '/orders', method: :post, class: "placeOrderForm" do |form| %>
            <%= form.submit 'Place order', 
            class: 'btn btn-outline-success w-100',
            data: {confirm: "Are you sure to place your order"} %>
        <% end %>
    </div>
</div>