config/routes.rb
Rails.application.routes.draw do
  post '/address', to: 'address#create'
  get '/cart', to: 'cart#index'
  post '/cart', to: 'cart#create'
  delete '/cart', to: 'cart#destroy'
  put '/cart', to: 'cart#update'
  delete '/cartAll', to: 'cart#destroyAll'
  get '/cart/checkout', to: 'cart#checkout'
  get '/cart/placeorder', to: 'cart#order', as: 'order'
  get '/allProducts', to: 'store#all'
  get '/category/:name', to: 'store#category'
  post '/store', to: 'store#filter'
  devise_for :users
  resources :products
  get '/admin/products', to: 'products#all'
  root 'store#index'
  get '/search', to: 'store#search'
  get '/orders', to: 'order#index'
  post '/orders', to: 'order#create'
  get '/orders/all', to: 'order#all'
  get '/orders/myorders/:id', to: 'order#show', as: 'order_details'
  delete '/orders/myorders/:id', to: 'order#destroy'
  post '/orders/myorders/:id/return', to: 'order#return'
  put '/orders/myorders/:id/payment', to: 'order#payment'
  put '/orders/myorders/:id/deliver', to: 'order#delivered'
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.order(created_at: :desc).limit(6)
  end

  def search
    @results = Product.all.where("lower(title) LIKE :search", search: "%#{params[:search]}%")
    if params[:search].present?
        render :partial => 'searchresults'
    else
        render :search
    end
  end

  # .order("price DESC")
  def all
    @pagy, @products = pagy(Product.all, items: 5)
  end

  def category
    @products = Product.where(category: params[:name])
  end

  def filter
    sortingParams = params[:sorting].present? ? params[:sorting] : "title"
    priceParams = params[:range].present? ? params[:range] : 10000000
    if params[:catArray].present?
      @pagy, @products = pagy(Product.with_sort(sortingParams).with_price(priceParams).with_category(params[:catArray]), items: 5)
    else 
      @pagy, @products = pagy(Product.with_sort(sortingParams).with_price(priceParams), items: 5)
    end
    render :partial => 'showproducts'
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/_filters.html.erb
<div class="row">
    <div class="col-md-3">
        <h5 class="fw-bolder fst-italic"> Categories: </h5>
        <%= form_tag(store_path, :method => "post", 
            class: 'd-flex flex-wrap categories') do %>
            <div class="form-check m-1">
                <%= check_box_tag :mobiles, "mobiles", 
                    false, class: "form-check-input categoryFilters" %>
                <%= label_tag :mobiles, 'mobiles', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= check_box_tag :accessories, "accessories", 
                    false, class: "form-check-input categoryFilters" %>
                <%= label_tag :accessories, 'accessories', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= check_box_tag :clothing, "clothing", 
                    false, class: "form-check-input categoryFilters" %>
                <%= label_tag :clothing, 'clothing', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= check_box_tag :sports, "sports", 
                    false, class: "form-check-input categoryFilters" %>
                <%= label_tag :sports, 'sports', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= check_box_tag :others, "others", 
                    false, class: "form-check-input categoryFilters" %>
                <%= label_tag :others, 'Others', 
                    class: "form-check-label" %>
            </div>
            
        <% end %>
    </div>
    <div class="col-md-4">
        <h5 class="fw-bolder fst-italic"> Price ranges: </h5>
        <%= form_tag(store_path, :method => "post",
            class: 'd-flex flex-wrap prices') do %>
            <div class="form-check m-1">
                <%= radio_button_tag :pricing, "500", 
                    false, class: "form-check-input priceFilters" %>
                <%= label_tag :pricing, '0 - 500', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= radio_button_tag :pricing, "2000", 
                    false, class: "form-check-input priceFilters" %>
                <%= label_tag :pricing, '0 - 2000', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= radio_button_tag :pricing, "5000", 
                    false, class: "form-check-input priceFilters" %>
                <%= label_tag :pricing, '0 - 5000', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= radio_button_tag :pricing, "10000", 
                    false, class: "form-check-input priceFilters" %>
                <%= label_tag :pricing, '0 - 10000', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= radio_button_tag :pricing, "20000", 
                    false, class: "form-check-input priceFilters" %>
                <%= label_tag :pricing, '0 - 20000', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= radio_button_tag :pricing, "", 
                    false, class: "form-check-input priceFilters" %>
                <%= label_tag :pricing, 'Any price', 
                    class: "form-check-label" %>
            </div>
        <% end %>
    </div>
    <div class="col-md-5">
        <h5 class="fw-bolder fst-italic"> Sort by: </h5>
        <%= form_tag(store_path, :method => "post",
            class: 'd-flex flex-wrap sortings') do %>
            <div class="form-check m-1">
                <%= radio_button_tag :sorting, "title", 
                    false, class: "form-check-input sortFilters" %>
                <%= label_tag :sorting, 'Sort by name (ASC)', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= radio_button_tag :sorting, "title DESC", 
                    false, class: "form-check-input sortFilters" %>
                <%= label_tag :sorting, 'Sort by name (DESC)', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= radio_button_tag :sorting, "price", 
                    false, class: "form-check-input sortFilters" %>
                <%= label_tag :sorting, 'Sort by price (ASC)', 
                    class: "form-check-label" %>
            </div>
            <div class="form-check m-1">
                <%= radio_button_tag :sorting, "price DESC", 
                    false, class: "form-check-input sortFilters" %>
                <%= label_tag :sorting, 'Sort by price (DESC)', 
                    class: "form-check-label" %>
            </div>
        <% end %>
    </div>
</div>

app/views/store/_searchresults.html.erb
<div class="d-flex flex-wrap">
<% @results.each do |result| %>
    <div class="card m-4" style="width: 18rem;">
        <%= image_tag result.image ,class: "card-img-top p-3" %>
        <div class="card-body">
            <h5 class="card-title">
                <%= result.title %>
            </h5>
            <h5 class="card-text">
                <%= result.price %>
            </h5>
            <%= link_to 'Go to Product', result, class: "btn btn-warning" %>
        </div>
    </div>
<% end %>
</div>

app/views/store/_showproducts.html.erb
<div>
     <div class="d-flex justify-content-center pt-3">
        <%== pagy_bootstrap_nav(@pagy) %>
    </div>
    <%= render @products %>
</div>

app/views/store/all.html.erb
<div>
    <%= render 'filters' %>
    <hr/>
    <div class="filterResults">
        <div class="d-flex justify-content-center pt-3">
            <%== pagy_bootstrap_nav(@pagy) %>
        </div>
        <%= render @products %>
        <div class="d-flex justify-content-center pt-3">
            <%== pagy_bootstrap_nav(@pagy) %>
        </div>
    </div>
</div>

<script type="text/javascript">
    let catArray = []
    let currentRange = ""
    let currentSort = ""
    $(".categoryFilters").on("click", function() {
        let authenticity_token = $(".categories input[name=authenticity_token]").val()
        let currentItem = $(this).val()
        if ( catArray.includes(currentItem) ){
            removeFrmArr(catArray, currentItem)
        }
        else{
            catArray.push(currentItem)
        }
        $.ajax({
            url: '/store', type: 'POST', dataType: 'html',
            data: {catArray, range: currentRange, authenticity_token, 
            sorting: currentSort},
            success: function(res) {
                $(".filterResults").html(res)
            },
            error: function(res) {
                console.error(res);
            }
        })
    })

    $(".priceFilters").on("click", function(){
        let authenticity_token = $(".prices input[name=authenticity_token]").val()
        currentRange = $(this).val()
        $.ajax({
            url: '/store', type: 'POST', dataType: 'html',
            data: {catArray,range: currentRange, 
                authenticity_token, sorting: currentSort},
            success: function(res) {
                $(".filterResults").html(res)
            },
            error: function(res) {
                console.error(res);
            }
        })
    })

    $(".sortFilters").on("click", function(){
        let authenticity_token = $(".sortings input[name=authenticity_token]").val()
        currentSort = $(this).val()
        $.ajax({
            url: '/store', type: 'POST', dataType: 'html',
            data: {catArray,range: currentRange, authenticity_token, 
            sorting: currentSort},
            success: function(res) {
                $(".filterResults").html(res)
            },
            error: function(res) {
                console.log(res);
                console.error(res);
            }
        })
    })
</script>

app/views/store/category.html.erb
<h3 class="text-center my-2">
    Products from <%= params[:name] %> category:
</h3>
<%=render @products %>

app/views/store/index.html.erb
<div class="py-4">
    <h2> Welcome to PC Store </h2>
    <hr />
    <div class="top-flex">
        <h5 class="customized-search">
            <%= link_to 'Search for users', search_path %>
        </h5>
    </div>
    <h3> Recently launched </h3>
    <div class="my-3 owl-carousel">
        <% @products.each do |product| %>
            <div class="card" style="width: 17rem;">
                <%= image_tag product.image, class: 'p-3',
                style: 'height:300px' %>
                <div class="card-body">
                    <h5 class="card-title">
                        <%= truncate(product.title, length: 40) %>
                    </h5>
                    <p class="card-text">
                        <%= truncate(product.description, length: 90) %>
                    </p>
                    <h5 class="card-text"><b> <%= product.price %> </b></h5>
                    <%= link_to 'View product', product, class: "btn btn-outline-dark" %>
                </div>
            </div>
        <% end %>
    </div>
</div>

<script>
    $(".owl-carousel").owlCarousel({
        loop: false,
        rewind: true, autoplay: true, autoplayTimeout: 3000,
        responsive:{
            0: {
                items:1,
                stagePadding: 30
            },
            600: {
                items:3
            },
            1024: {
                items: 4
            }
        }
    })
</script>

app/views/store/search.html.erb
<div class="searching-form">
    <%= form_tag(search_path, :method => "get", class: '') do %>  
    <div class="input-group">  
        <%= search_field_tag :search, params[:search],
             placeholder: "Search for users", class: "form-control" %> 
    </div>  
    <% end %>
</div>

<div class="searchRes my-4">
    
</div>

<script type="text/javascript">
    $(document).ready(function() {
        const debounce = (func, delay) => {
            let debounceTimer
            return function() {
                const context = this
                const args = arguments
                    clearTimeout(debounceTimer)
                        debounceTimer
                    = setTimeout(() => func.apply(context, args), delay)
            }
        } 
        function prompt() {
            if ($(this).val().trim().length > 0){
                $.ajax({
                    url: '/search', 
                    data: {search: $(this).val()},
                    success: function(res) {
                        $(".searchRes").html(res)
                    }
                });
            }
        }
        $("#search").keyup(debounce(prompt, 1000));
    });
</script>