config/routes.rb
Rails.application.routes.draw do
  post '/address', to: 'address#create'
  get '/cart', to: 'cart#index'
  post '/cart', to: 'cart#create'
  delete '/cart', to: 'cart#destroy'
  put '/cart', to: 'cart#update'
  delete '/cartAll', to: 'cart#destroyAll'
  get '/cart/checkout', to: 'cart#checkout'
  get '/cart/placeorder', to: 'cart#order', as: 'order'
  get '/allProducts', to: 'store#all'
  get '/category/:name', to: 'store#category'
  post '/store', to: 'store#filter'
  devise_for :users
  resources :products
  get '/admin/products', to: 'products#all'
  root 'store#index'
  get '/search', to: 'store#search'
  get '/orders', to: 'order#index'
  post '/orders', to: 'order#create'
  get '/orders/all', to: 'order#all'
  get '/orders/myorders/:id', to: 'order#show', as: 'order_details'
  delete '/orders/myorders/:id', to: 'order#destroy'
  post '/orders/myorders/:id/return', to: 'order#return'
  put '/orders/myorders/:id/payment', to: 'order#payment'
  put '/orders/myorders/:id/deliver', to: 'order#delivered'
end

app/views/layouts/_footer.html.erb
<nav class="navbar fixed-bottom navbar-light" 
    style="background-color: #0E1F2F">
  <div class="container-fluid d-flex justify-content-center align-items-center">
    <h6 class="text-white py-2 pb-1"> Made by Sravan #promptcloud21 </h6>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark" 
    style="background-color: #EE6360">
  <div class="container-fluid">
    <%= link_to 'PC Store', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'All products', allProducts_path, class: "nav-link active" %>
        </li>
        <%# admin %>
        <% if user_signed_in? && current_user.admin? %>
          <li class="nav-item">
            <%= link_to '+ New product', new_product_path , 
              class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to '- All orders', orders_all_path , 
              class: "nav-link active" %>
          </li>
          
        <% end %>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop by category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Mobiles', '/category/mobiles', class: "dropdown-item" %>
            <%= link_to 'Gadgets', '/category/accessories', class: "dropdown-item" %>
            <%= link_to 'Clothing', '/category/clothing', class: "dropdown-item" %>
            <%= link_to 'Sports', '/category/sports', class: "dropdown-item" %>
            <%= link_to 'Others', '/category/others', class: "dropdown-item" %>
          </ul>
        </li>

        <% if user_signed_in? %>
            <li>
              <%= link_to 'Edit profile', 
                edit_user_registration_path, class: "nav-link active" %>
            </li>
            <li>
                <%= link_to 'Logout', destroy_user_session_path, method: "delete",
                class: "nav-link active", data: {confirm: "Are you sure to logout"}  %>
            </li>
            <li class="nav-item position-relative">
                <%= link_to "Cart", cart_path, class: "nav-link active"%>
                <span class="position-absolute top-0 start-100 translate-middle
                  mt-2 badge rounded-pill bg-white text-danger" id="cartCount">
                    <%= Cart.current_user_cart_items(current_user.id).count %>
                </span>
            </li>
            <li class="ms-3 nav-item">
                <%= link_to "My orders", orders_path, class: "nav-link active" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Signup', new_user_registration_path, class: "nav-link active" %>
           </li>
           <li class="nav-item">
              <%= link_to 'Login', new_user_session_path, class: "nav-link active" %>
           </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous">
    <%= stylesheet_link_tag 'datatables', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'searchbar' %>
    <%= javascript_include_tag 'datatables' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container my-5 py-3">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-info"><%=
          message %></div>
        <% end %>
        <div class="toast">
            <div class="toast-header"> </div>
            <div class="toast-body"> </div>
          </div>
        <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
    crossorigin="anonymous">
    </script>
  </body>
</html>